<a href="https://colab.research.google.com/github/tom-d-c/sports-analytics/blob/dev-f1/yuki_vs_liam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd

def to_seconds(time_str):
    minutes, seconds = map(float, time_str.split(':'))
    return minutes * 60 + seconds

data = [
    {'Name': 'USA', 'Time_Liam': to_seconds('1:33.339'), 'Time_Yuki': to_seconds('1:33.795')},
    {'Name': 'MEXICO', 'Time_Liam': to_seconds('1:17.380'), 'Time_Yuki': to_seconds('1:17.182')},
    {'Name': 'BRASIL', 'Time_Liam': to_seconds('1:30.758'), 'Time_Yuki': to_seconds('1:29.172')},
    {'Name': 'LAS VEGAS', 'Time_Liam': to_seconds('1:34.087'), 'Time_Yuki': to_seconds('1:33.789')},
    {'Name': 'QATAR', 'Time_Liam': to_seconds('1:22.411'), 'Time_Yuki': to_seconds('1:22.364')},
    {'Name': 'ABU DHABI', 'Time_Liam': to_seconds('1:23.733'), 'Time_Yuki': to_seconds('1:23.735')},
]

df = pd.DataFrame(data)
df

        Name  Time_Liam  Time_Yuki
0        USA     93.339     93.795
1     MEXICO     77.380     77.182
2     BRASIL     90.758     89.172
3  LAS VEGAS     94.087     93.789
4      QATAR     82.411     82.364
5  ABU DHABI     83.733     83.735

In [13]:
# Calculate the percentage difference between 'Time' and 'Time_Max'
df['Percentage_Difference'] = ((df['Time_Liam'] - df['Time_Yuki']) / (df['Time_Liam'] + df['Time_Yuki'])/2) * 100

# Group by 'Name' and calculate the average percentage difference
average_percentage_difference = df['Percentage_Difference'].mean()

# Group by 'Name' and calculate the standard deviation of the percentage difference
std_percentage_difference = df['Percentage_Difference'].std()

print(f"Average Percentage Difference: {average_percentage_difference:.2f}%")
print(f"Standard Deviation of Percentage Difference: {std_percentage_difference:.2f}%")

Average Percentage Difference: 0.08%
Standard Deviation of Percentage Difference: 0.19%

In [14]:
df

        Name  Time_Liam  Time_Yuki  Percentage_Difference
0        USA     93.339     93.795              -0.121838
1     MEXICO     77.380     77.182               0.064052
2     BRASIL     90.758     89.172               0.440727
3  LAS VEGAS     94.087     93.789               0.079308
4      QATAR     82.411     82.364               0.014262
5  ABU DHABI     83.733     83.735              -0.000597

In [32]:
import plotly.graph_objects as go

# Create a list of names in the desired order
names = df.Name.tolist()

# Create a list of colors
color = 'darkblue'

fig = go.Figure()
W = 1200
H = 600

for name in names:
    value = df.Percentage_Difference[df.Name == name].values[0]  # Extract single value
    label = "YUKI" if value > 0 else "LIAM"

    fig.add_trace(go.Bar(
        x=[name],
        y=[value],
        name=name,
        marker_color=color,
        text=label,  # Add label
        textposition="inside",  # Ensure text is inside the bars
        insidetextanchor="middle",
        textfont=dict(color="white")  # Make text white
    ))

fig.update_layout(
    title='How Laim and Yuki performed in Q1 in the same car',
    title_x=0.5,  # Center the title
    yaxis_title='Q1 Gap Liam - Yuki (%)',
    showlegend=False,
    plot_bgcolor='white',
    width=W,
    height=H
)

fig.update_yaxes(range=[-0.5, 0.5], dtick=0.25)
fig.update_yaxes(zeroline=True, zerolinecolor=color, zerolinewidth=.1, showline=True, linewidth=1, linecolor='black', ticks='outside')

fig.show()